### ISSUE TITLE
When adding event decorator, `OnEventClickListener` doesn't receive Event anymore

### ISSUE THREAD

**Issue by Diederikjh** [memfis19/Cadar#10]
Hi,
I am playing around with the sample app, and added a `OnEventClickListener` object to the `listCalendar` member in the `ListCalendarActivity`.  

When I just add the event click listener, the event always comes back as null.

If I remove the line `listBuilder.setEventLayout(R.layout.custom_event_layout, eventDecoratorFactory);` however, it seems to work again.  Looks to me like the event decorator factory, doesn't save the event when binding the view.

**Comment by memfis19** [comment]
Hi, I've just fixed it. Will be available in 1-2 hrs in version `0.2.2`.

**Comment by memfis19** [comment]
Will be available in 1-2 hrs via jCenter. Code is already available.

**Comment by Diederikjh** [comment]
Cool, looks like this fixed it. 
Thanks
