### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by Abdullah-Nasim** [memfis19/Cadar#2]
I am facing a lot of compilation errors even while compiling the sample project.

![capture](https://cloud.githubusercontent.com/assets/24429141/20959971/5c17a3ae-bc77-11e6-8b20-c9e989c2185c.PNG)

**Comment by memfis19** [comment]
Hi, thanks I'll look at it.

**Comment by memfis19** [comment]
Hi, this are warnings which is safe to ignore. I will add some proguard rules but anyway they will not replace current errors in debug build type. As one more way to solve I'll try to update ```ICal4J``` library which causes this errors.
