### ISSUE TITLE
Hiding the Days in month

### ISSUE THREAD

**Issue by Abdullah-Nasim** [memfis19/Cadar#3]
How can I hide the days which are not there in particular month ?

**Comment by memfis19** [comment]
Hi, thanks for the report. This feature was missed - my fault. I've just fixed it and commit changes, you can check it now. I'm not sure about how soon it will be available via JCenter, but you can check the sources.
How it works now:
1. In case you are using default month day displaying - then just set ```setDisplayDaysOutOfMonth``` in ```MonthCalendarConfiguration``` to true.
2. In case you are using custom decorator: current month will  be passed as parameter, you can compare it i.e. ```DateUtils.isSameMonth(...)```.

Please look at example project ```MonthCalendarActivity``` and ```MonthListCalendarInteractionActivity``` relatively.
