### ISSUE TITLE
Changing the parallax images

### ISSUE THREAD

**Issue by Abdullah-Nasim** [memfis19/Cadar#6]
Is there any way to change the parallax images and customize the title of month shown above the image for example change the position and changing the font color of the title etc ?

**Comment by memfis19** [comment]
Hi, You can do it using decorators. ```ListCalendarConfiguration``` contains next ones methods: 
1. ```setEventLayout```
2. ```setWeekLayout```
3. ```setMonthLayout```
with the help of this methods you can customize event, week, month representation in list calendar.

**Comment by Abdullah-Nasim** [comment]
How to implement abstract method on scroll listener ? I am trying to call setMonthLayout ? It comes with monthDecorator

**Comment by memfis19** [comment]
I'll add sample in nearest time.

**Comment by memfis19** [comment]
Added in ```0.2.0```.

**Comment by AndroidDeveloperLB** [comment]
The images move in parallax ? I don't see it...
